//
//  LUTCubeLoader.swift
//  OneTake
//
//  Owns: Loading `.cube` color tables as Metal-ready float data + dimensions.
//  Why: Two on-disk flavors exist — legacy raw-binary RGBA dumps (4 MB means
//  64³) and Adobe text generated by `tools/generate_luts.py`. Sniffing keeps
//  old files byte-identical while new SIZE-32 text cubes ship ~5× smaller.
//  See: docs/ARCHITECTURE.md §6 + openspec/specs/trim-color-export/spec.md
//
import CoreImage
import Foundation

enum LUTCubeLoader {
    /// Supported lattice sizes (spec: 16/32/64; anything else → default).
    static let supportedDimensions = [16, 32, 64]
    static let defaultDimension = 64

    private static var cache: [String: Data] = [:]
    private static let cacheLock = NSLock() // tests + UI hit the loader off-main

    /// Metal-ready RGBA float32 data, or nil for Natural / missing / corrupt.
    /// Legacy binary passes through untouched; Adobe text is parsed.
    static func data(for preset: LUTPreset) -> Data? {
        if preset == .natural {
            return nil
        }
        cacheLock.lock()
        let cached = cache[preset.rawValue]
        cacheLock.unlock()
        if let cached {
            return cached
        }
        guard let url = Bundle.main.url(forResource: preset.rawValue, withExtension: "cube"),
              let raw = try? Data(contentsOf: url),
              let parsed = parse(raw: raw)
        else {
            debugPrint("[LUT] missing or unreadable cube for \(preset.rawValue)")
            return nil
        }
        cacheLock.lock()
        cache[preset.rawValue] = parsed.data
        cacheLock.unlock()
        return parsed.data
    }

    /// Lattice dimension for `preset` (parsed, else 64). Pure lookup for tests.
    static func dimension(for preset: LUTPreset) -> Int {
        guard preset != .natural,
              let url = Bundle.main.url(forResource: preset.rawValue, withExtension: "cube"),
              let raw = try? Data(contentsOf: url)
        else { return defaultDimension }
        return dimension(in: raw)
    }

    /// Dimension sniffing: Adobe `LUT_3D_SIZE` header wins; else byte-count
    /// match for raw binary (`N³×16` RGBA float32); else the default.
    static func dimension(in raw: Data) -> Int {
        if let size = adobeSize(in: raw), supportedDimensions.contains(size) {
            return size
        }
        for size in supportedDimensions where raw.count == size * size * size * 16 {
            return size
        }
        return defaultDimension
    }

    /// Adobe text → interleaved RGBA float32 (R fastest, alpha 1).
    /// Returns nil unless exactly `dimension³` triplets parse in range.
    static func floatData(from text: String, dimension size: Int) -> Data? {
        var floats: [Float] = []
        floats.reserveCapacity(size * size * size * 4)
        var count = 0
        for rawLine in text.components(separatedBy: .newlines) {
            let line = rawLine.trimmingCharacters(in: .whitespaces)
            if line.isEmpty || line.hasPrefix("#") || line.contains("LUT_") || line.contains("DOMAIN_") || line.hasPrefix("TITLE") {
                continue
            }
            let parts = line.split(separator: " ")
            guard parts.count >= 3,
                  let red = Float(parts[0]), let green = Float(parts[1]), let blue = Float(parts[2]),
                  (0 ... 1).contains(red), (0 ... 1).contains(green), (0 ... 1).contains(blue)
            else { return nil }
            floats.append(contentsOf: [red, green, blue, 1.0])
            count += 1
            if count == size * size * size {
                break
            }
        }
        guard count == size * size * size else { return nil }
        return floats.withUnsafeBufferPointer { Data(buffer: $0) }
    }

    static func filter(for preset: LUTPreset, inputImage: CIImage) -> CIImage? {
        guard preset != .natural else { return inputImage }
        guard let data = data(for: preset) else { return inputImage }
        guard let filter = CIFilter(name: "CIColorCube") else { return inputImage }
        filter.setValue(inputImage, forKey: kCIInputImageKey)
        filter.setValue(Float(dimension(for: preset)), forKey: "inputCubeDimension")
        filter.setValue(data, forKey: "inputCubeData")
        return filter.outputImage ?? inputImage
    }

    // MARK: - Parsing

    private static func parse(raw: Data) -> (dimension: Int, data: Data)? {
        if let size = adobeSize(in: raw), let data = parseAdobe(raw: raw, size: size) {
            return (size, data)
        }
        let size = dimension(in: raw)
        guard raw.count == size * size * size * 16 else { return nil }
        return (size, raw) // Legacy raw binary: pass through untouched.
    }

    private static func parseAdobe(raw: Data, size: Int) -> Data? {
        guard supportedDimensions.contains(size) else { return nil }
        guard let text = String(data: raw, encoding: .utf8) else { return nil }
        return floatData(from: text, dimension: size)
    }

    private static func adobeSize(in raw: Data) -> Int? {
        guard let text = String(data: raw.prefix(2048), encoding: .utf8) else { return nil }
        for rawLine in text.components(separatedBy: .newlines) {
            let line = rawLine.trimmingCharacters(in: .whitespaces)
            guard line.hasPrefix("LUT_3D_SIZE") else { continue }
            let parts = line.split(separator: " ")
            if parts.count >= 2, let size = Int(parts[1]) {
                return size
            }
            return nil
        }
        return nil
    }
}
